<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0</TargetFrameworks>
		<StaticWebAssetBasePath>/</StaticWebAssetBasePath>
	</PropertyGroup>

	<PropertyGroup>
		<Title>Jumoo.TranslationManager.OpenAi</Title>
		<PackageId>Jumoo.TranslationManager.OpenAi</PackageId>
		<Product>Jumoo.TranslationManager.OpenAi</Product>

		<Authors>Jumoo</Authors>
		<Description></Description>
		<releaseNotes></releaseNotes>

		<Copyright>Jumoo 2023</Copyright>

		<PackageTags>umbraco, umbraco-cms, translations, umbraco-marketplace</PackageTags>
		<PackageProjectUrl>https://github.com/Jumoo/Jumoo.TranslationManager.OpenAi</PackageProjectUrl>
		<RepositoryUrl>https://github.com/Jumoo/Jumoo.TranslationManager.OpenAi</RepositoryUrl>
	</PropertyGroup>

	<PropertyGroup>
		<PackageIcon>logo.png</PackageIcon>
		<PackageReadmeFile>readme.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="logo.png" Pack="true" PackagePath="\" />
		<None Include="readme.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup Condition="$(DefineConstants.Contains(UMB_13_ONLY))">
		<PackageReference Include="Jumoo.TranslationManager.Core" Version="13.0.0" />
		<PackageReference Include="Jumoo.TranslationManager.Serializers" Version="13.0.0" />
		<PackageReference Include="Umbraco.Cms.Web.BackOffice" Version="13.0.0" />
	</ItemGroup>

	<ItemGroup Condition="$(DefineConstants.Contains(UMB_16_ONLY))">
		<PackageReference Include="Jumoo.TranslationManager.Core" Version="16.0.0" />
		<PackageReference Include="Jumoo.TranslationManager.Serializers" Version="16.0.0" />
		<PackageReference Include="Umbraco.Cms.Api.Management" Version="16.0.0" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Azure.AI.OpenAI" Version="2.1.0-beta.2" />
		<PackageReference Include="Betalgo.Ranul.OpenAI" Version="9.0.1" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="wwwroot\App_Plugins\Translations.OpenAi\modern\" />
	</ItemGroup>
</Project>
